  ############################################################################
  ## 
  ##  Makefile.bcc  
  ## 
  ##
  ##  AGENT++ API Version 3.5.22c
  ##  -----------------------------------------------
  ##  Copyright (C) 2000-2004 Frank Fock, Jochen Katz
  ##  
  ##  LICENSE AGREEMENT
  ##
  ##  WHEREAS,  Frank  Fock  and  Jochen  Katz  are  the  owners of valuable
  ##  intellectual  property rights relating to  the AGENT++ API and wish to
  ##  license AGENT++ subject to the  terms and conditions set forth  below;
  ##  and
  ##
  ##  WHEREAS, you ("Licensee") acknowledge  that Frank Fock and Jochen Katz
  ##  have the right  to grant licenses  to the intellectual property rights
  ##  relating to  AGENT++, and that you desire  to obtain a license  to use
  ##  AGENT++ subject to the terms and conditions set forth below;
  ##
  ##  Frank  Fock    and Jochen   Katz   grants  Licensee  a  non-exclusive,
  ##  non-transferable, royalty-free  license  to use   AGENT++ and  related
  ##  materials without  charge provided the Licensee  adheres to all of the
  ##  terms and conditions of this Agreement.
  ##
  ##  By downloading, using, or  copying  AGENT++  or any  portion  thereof,
  ##  Licensee  agrees to abide  by  the intellectual property  laws and all
  ##  other   applicable laws  of  Germany,  and  to all of   the  terms and
  ##  conditions  of this Agreement, and agrees  to take all necessary steps
  ##  to  ensure that the  terms and  conditions of  this Agreement are  not
  ##  violated  by any person  or entity under the  Licensee's control or in
  ##  the Licensee's service.
  ##
  ##  Licensee shall maintain  the  copyright and trademark  notices  on the
  ##  materials  within or otherwise  related   to AGENT++, and  not  alter,
  ##  erase, deface or overprint any such notice.
  ##
  ##  Except  as specifically   provided in  this  Agreement,   Licensee  is
  ##  expressly   prohibited  from  copying,   merging,  selling,   leasing,
  ##  assigning,  or  transferring  in  any manner,  AGENT++ or  any portion
  ##  thereof.
  ##
  ##  Licensee may copy materials   within or otherwise related   to AGENT++
  ##  that bear the author's copyright only  as required for backup purposes
  ##  or for use solely by the Licensee.
  ##
  ##  Licensee may  not distribute  in any  form  of electronic  or  printed
  ##  communication the  materials  within or  otherwise  related to AGENT++
  ##  that  bear the author's  copyright, including  but  not limited to the
  ##  source   code, documentation,  help  files, examples,  and benchmarks,
  ##  without prior written consent from the authors.  Send any requests for
  ##  limited distribution rights to fock@agentpp.com.
  ##
  ##  Licensee  hereby  grants  a  royalty-free  license  to  any  and   all 
  ##  derivatives  based  upon this software  code base,  that  may  be used
  ##  as a SNMP  agent development  environment or a  SNMP agent development 
  ##  tool.
  ##
  ##  Licensee may  modify  the sources  of AGENT++ for  the Licensee's  own
  ##  purposes.  Thus, Licensee  may  not  distribute  modified  sources  of
  ##  AGENT++ without prior written consent from the authors. 
  ##
  ##  The Licensee may distribute  binaries derived from or contained within
  ##  AGENT++ provided that:
  ##
  ##  1) The Binaries are  not integrated,  bundled,  combined, or otherwise
  ##     associated with a SNMP agent development environment or  SNMP agent
  ##     development tool; and
  ##
  ##  2) The Binaries are not a documented part of any distribution material. 
  ##
  ##
  ##  THIS  SOFTWARE  IS  PROVIDED ``AS  IS''  AND  ANY  EXPRESS OR  IMPLIED
  ##  WARRANTIES, INCLUDING, BUT NOT LIMITED  TO, THE IMPLIED WARRANTIES  OF
  ##  MERCHANTABILITY AND FITNESS FOR  A PARTICULAR PURPOSE  ARE DISCLAIMED.
  ##  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  ##  INDIRECT,   INCIDENTAL,  SPECIAL, EXEMPLARY,  OR CONSEQUENTIAL DAMAGES
  ##  (INCLUDING,  BUT NOT LIMITED  TO,  PROCUREMENT OF SUBSTITUTE  GOODS OR
  ##  SERVICES; LOSS OF  USE,  DATA, OR PROFITS; OR  BUSINESS  INTERRUPTION)
  ##  HOWEVER CAUSED  AND ON ANY THEORY  OF  LIABILITY, WHETHER IN CONTRACT,
  ##  STRICT LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
  ##  IN  ANY WAY OUT OF  THE USE OF THIS  SOFTWARE,  EVEN IF ADVISED OF THE
  ##  POSSIBILITY OF SUCH DAMAGE. 
  ##
  ##
  ##  Stuttgart, Germany, Thu Jan 13 00:12:31 CET 2005 
  ##  
  ##########################################################################*

#  Makefile.bcc -- Borland C++ compatible makefile for Agent++
#                  
#  To make all targets, type: "make -fMakefile.bcc"
#  To make the static library, type: "make -fMakefile.bcc lib"
#  To make the dynamic link library, type: "make -fMakefile.bcc dll"
#
#  Luis F. Pollo (pollo@inf.ufrgs.br)
#  Porto Alegre, RS, Brazil - April 19, 2002
#  -------------------------------------------



CPP      = bcc32
CPPFLAGS = -P -tWM -DWIN32=1 -DAGENT_PP_NATIVE_EXPORTS=1
W32LIBS  = wsock32.lib

SNMPINC		= ..\..\snmp++\include

AGENTLIBDIR	= ..\lib
AGENTLIB	= agent_pp.lib
AGENTDLL	= agent_pp.dll

INC		= ..\include
INCLUDES	= -I$(INC) -I$(SNMPINC)

HEADERS		= $(INC)\agent++.h \
		$(INC)\agentpp_simulation_mib.h \
		$(INC)\avl_map.h \
		$(INC)\entry.h \
		$(INC)\List.h \
		$(INC)\log.h \
		$(INC)\map.h \
		$(INC)\mib.h \
		$(INC)\mib_avl_map.h \
		$(INC)\mib_complex_entry.h \
		$(INC)\mib_context.h \
		$(INC)\mib_entry.h \
		$(INC)\mib_map.h \
		$(INC)\mib_policy.h \
		$(INC)\mib_proxy.h \
		$(INC)\notification_log_mib.h \
		$(INC)\notification_originator.h \
		$(INC)\oidx_defs.h \
		$(INC)\oidx_ptr.h \
		$(INC)\proxy_forwarder.h \
		$(INC)\request.h \
		$(INC)\sim_mib.h \
		$(INC)\snmp_community_mib.h \
		$(INC)\snmp_counters.h \
		$(INC)\snmp_group.h \
		$(INC)\snmp_notification_mib.h \
		$(INC)\snmp_pp_ext.h \
		$(INC)\snmp_proxy_mib.h \
		$(INC)\snmp_request.h \
		$(INC)\snmp_target_mib.h \
		$(INC)\snmp_textual_conventions.h \
		$(INC)\system_group.h \
		$(INC)\threads.h \
		$(INC)\tools.h \
		$(INC)\v3_mib.h \
		$(INC)\vacm.h \
		$(INC)\vacm_class.h

OBJS		= mib.obj log.obj threads.obj tools.obj mib_entry.obj snmp_group.obj \
		  request.obj snmp_pp_ext.obj snmp_request.obj mib_proxy.obj \
		  snmp_counters.obj system_group.obj \
		  mib_avl_map.obj mib_map.obj mib_context.obj \
		  v3_mib.obj vacm.obj snmp_textual_conventions.obj \
		  snmp_target_mib.obj snmp_notification_mib.obj \
		  notification_originator.obj avl_map.obj map.obj sim_mib.obj \
		  agentpp_simulation_mib.obj mib_policy.obj \
		  snmp_proxy_mib.obj snmp_community_mib.obj \
		  mib_complex_entry.obj proxy_forwarder.obj notification_log_mib.obj


.SUFFIXES: .cpp

.cpp.obj:
    $(CPP) $(CPPFLAGS) $(INCLUDES) -c {$? }

all: lib

$(AGENTLIB): $(OBJS)
	-@if not exist $(AGENTLIBDIR) mkdir $(AGENTLIBDIR)
	tlib /P32 $(AGENTLIBDIR)\$(AGENTLIB) /a $(OBJS)	

lib: $(AGENTLIB)

$(AGENTDLL): $(OBJS)
	-@if not exist $(AGENTLIBDIR) mkdir $(AGENTLIBDIR)
	bcc32 -tWD -e$(AGENTLIBDIR)\$(AGENTDLL) $(OBJS)	$(W32LIBS)

dll: $(AGENTDLL)

clean:
   @echo Cleaning up...
   -@if exist *.obj del *.obj                                 >nul
   -@if exist $(AGENTLIBDIR)\*.lib del $(AGENTLIBDIR)\*.lib   >nul
   -@if exist $(AGENTLIBDIR)\*.dll del $(AGENTLIBDIR)\*.dll   >nul
   -@if exist $(AGENTLIBDIR)\*.tds del $(AGENTLIBDIR)\*.tds   >nul
   -@if exist *.exe del *.exe                                 >nul

#
#  Dependency rules
#
$(OBJS): $(HEADERS)