name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Which environment to run this on'
        required: true
        default: 'development'
        options:
          - development
          - production
      tag:
        type: string
        description: 'Which tag to utilize'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
